using System;

class Program {
    static void Main() {
        Console.Write("Ingrese un número entero: ");
        int entero = int.Parse(Console.ReadLine());

        Console.Write("Ingrese un número flotante: ");
        float flotante = float.Parse(Console.ReadLine());

        onsole.Write("Ingrese un carácter: ");
        char caracter = char.Parse(Console.ReadLine());
        
        Console.Write("Ingrese una cadena de caracteres: ");
        string cadena = Console.ReadLine();
    }
}